//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSQLServerRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle : IDisposable
    {
        public int IdVehicle { get; set; }
        public string Registration { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public decimal Price { get; set; }
        public int Type { get; set; }
    
        public virtual Type Type1 { get; set; }
        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
}
